version: "3"
services:
  database:
    image: postgres:15.3-bullseye
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=parking-control"
    ports:
      - "5441:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - database-network
  pg-admin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=emanuelwork1@gmail.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "1234:80"
    depends_on:
      - database
    networks:
      - database-network

volumes:
  pg-data:

networks:
  database-network:
    driver: bridge
